interval: 5
variables:
  - key: hostname
    value:
      name: bash
      arguments:
        - -c
        - hostname | tr "\n" " " | sed 's/ *$//g'

metric:
  - key: '{{.Variables.hostname}}.memory_used'
    value:
      name: bash
      arguments:
        - -c
        - free -m | awk 'NR==2{printf "%s\n", $3 }'
  - key: '{{.Variables.hostname}}.memory_total'
    value:
      name: bash
      arguments:
        - -c
        - free -m | awk 'NR==2{printf "%s\n", $2 }'
