interval: 10
metric:
  - key: memory_used
    value:
      name: bash
      arguments:
        - -c
        - free -m | awk 'NR==2{printf "%s\n", $3 }'
  - key: memory_total
    value:
      name: bash
      arguments:
        - -c
        - free -m | awk 'NR==2{printf "%s\n", $2 }'
